<!--
/**
 * @category  Netresearch
 * @package   Netresearch_Magebid
 * @author    André Herrn <andre.herrn@netresearch.de>
 * @copyright 2010 André Herrn | Netresearch GmbH & Co.KG (http://www.netresearch.de)
 * @link      http://www.magebid.de/
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
-->

<div class="content-header">
    <h3 class="icon-head head-products"><?php echo $this->getHeaderText() ?></h3>
</div>

<?php echo $this->getChildHtml('grid') ?>