<?php
// autogenerated file 05.05.2008 16:30
// $Id: $
// $Log: $
//
//
require_once 'EbatNsCsSetExt_CharacteristicsSetType.php';
require_once 'EbatNs_ComplexType.php';

/**
 *  
 *
 *
 */
class EbatNsCsSetExt_CharacteristicsSetArrayType extends EbatNs_ComplexType
{
	/**
	 * @var EbatNsCsSetExt_CharacteristicsSetType
	 */
	protected $CharacteristicsSet;

	/**
	 * @return EbatNsCsSetExt_CharacteristicsSetType
	 * @param integer $index 
	 */
	function getCharacteristicsSet($index = null)
	{
		if ($index !== null) {
			return $this->CharacteristicsSet[$index];
		} else {
			return $this->CharacteristicsSet;
		}
	}
	/**
	 * @return void
	 * @param EbatNsCsSetExt_CharacteristicsSetType $value 
	 * @param  $index 
	 */
	function setCharacteristicsSet($value, $index = null)
	{
		if ($index !== null) {
			$this->CharacteristicsSet[$index] = $value;
		} else {
			$this->CharacteristicsSet = $value;
		}
	}
	/**
	 * @return void
	 * @param EbatNsCsSetExt_CharacteristicsSetType $value 
	 */
	function addCharacteristicsSet($value)
	{
		$this->CharacteristicsSet[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('EbatNsCsSetExt_CharacteristicsSetArrayType', 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd');
		$this->_elements = array_merge($this->_elements,
			array(
				'CharacteristicsSet' =>
				array(
					'required' => false,
					'type' => 'EbatNsCsSetExt_CharacteristicsSetType',
					'nsURI' => 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
