<?php
// autogenerated file 18.05.2010 12:34
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * The Timestamp field indicates the official eBay system time in GMT.For 
 * information about converting between GMT and other time zones,see "Time Values" 
 * in the Data Types appendix in the eBay Web Services guide. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GeteBayOfficialTimeResponseType.html
 *
 */
class GeteBayOfficialTimeResponseType extends AbstractResponseType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GeteBayOfficialTimeResponseType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__])) {
			self::$_elements[__CLASS__] = array();
		}
	}
}
?>
