<!--
/**
 * @category  Mbid
 * @package   Mbid_Magebid
 * @author    André Herrn <info@magebid.com>
 * @copyright 2010 André Herrn | Netresearch GmbH & Co.KG (http://www.netresearch.de)
 * @link      http://www.magebid.com/
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
-->

<?php $_htmlId      = $this->getElement()->getHtmlId()?>
<?php $_htmlClass   = $this->getElement()->getClass()?>
<?php $_htmlName    = $this->getElement()->getName()?>
<?php $_allowEdit    = $this->getAllowEdit()?>

<tr>
    <td class="label"><?php echo Mage::helper('magebid')->__('Shipping Methods') ?></td>
    <td colspan="10" class="grid shipping">
    <table cellspacing="0" class="data border" id="shipping_table">
        <col width="400" />
        <col width="50" />
		<col width="50" />
        <?php if ($_allowEdit): ?><col width="40" /><?php endif; ?>
        <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('magebid')->__('Shipping Methods') ?></th>
                <th><?php echo Mage::helper('magebid')->__('Shipping Price') ?></th>
				<th><?php echo Mage::helper('magebid')->__('Additional Shipping Price') ?></th>
                 <?php if ($_allowEdit): ?><th class="last"><?php echo Mage::helper('catalog')->__('Action') ?></th><?php endif; ?>
            </tr>
            <tr id="<?php echo $_htmlId ?>_add_template" class="template no-display">
                <td>
                <select disabled="no-template" class="<?php echo $_htmlClass ?> paymethod required-entry" name="<?php echo $_htmlName ?>[__index__][shipping_method]" id="shipping_method_row___index___shipping_methods">
                    <?php foreach ($this->getShippingMethods() as $_shippingCode=>$_shippingDescription): ?>
                    <option value="<?php echo $_shippingCode ?>"><?php echo htmlspecialchars($_shippingDescription) ?></option>
                    <?php endforeach ?>
                </select>
                </td>
                <td>
                    <input disabled="no-template" class="<?php echo $_htmlClass ?>" type="text" name="<?php echo $_htmlName ?>[__index__][price]" value="'#{price}'" />
                </td>
                <td>
                    <input disabled="no-template" class="<?php echo $_htmlClass ?>" type="text" name="<?php echo $_htmlName ?>[__index__][add_price]" value="'#{add_price}'" />
                </td>				
                <?php if ($_allowEdit): ?><td class="last"><input type="hidden" name="<?php echo $_htmlName ?>[__index__][delete]" class="delete" disabled="no-template" value="" /><button title="Delete Shipping Method" class="scalable delete icon-btn delete-shipping-method" onclick="shippingMethodControl.deleteItem(event);return false"><span>Delete</span></button></td><?php endif; ?>
            </tr>
        </thead>
		 <?php if ($_allowEdit): ?>
        <tfoot>
            <tr>
               <td colspan="4" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
            </tr>
        </tfoot>
		<?php endif; ?>
        <tbody id="<?php echo $_htmlId ?>_container">
        </tbody>
    </table>
	
	
<script type="text/javascript">
//<![CDATA[
    var shippingMethodControl = {
        template : new Template('<tr>' + $('<?php echo $_htmlId ?>_add_template').innerHTML.replace(/__index__/g, '#{index}').replace(/ disabled="?no-template"?/g, '').replace(/ disabled/g, '').replace(/="'([^']*)'"/g, '="$1"') + '</tr>'),
        itemsCount : 0,
        deleteButton: false,
        addItem  : function () {
            var data = {};
            data.shipping = '';
            data.price = '';
			data.add_price = '';
            data.index = this.itemsCount++;
            if(arguments.length == 3) {
                data.shipping      = arguments[0];
                data.price      = arguments[1];
				data.add_price      = arguments[2];
            }
            Element.insert($('<?php echo $_htmlId ?>_container'), {'bottom':this.template.evaluate(data)});
            $('shipping_method_row_'+data.index+'_shipping_methods').value = data.shipping;
        },
        disableElement: function(elem) {
            elem.disabled = true
            elem.addClassName('disabled');
        },
        deleteItem : function(event) {
            var tr = Event.findElement(event, 'tr');
            if (tr) {
				//Element.remove(tr);
                Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                Element.hide(tr);
                Element.addClassName(tr, 'no-display template');					
            }
        }
    }
    <?php foreach ($this->getValues() as $_item): ?>
    shippingMethodControl.addItem('<?php echo $_item['shipping_method'] ?>', '<?php echo sprintf('%.2f', $_item['price']) ?>', '<?php echo sprintf('%.2f', $_item['add_price']) ?>');
	<?php endforeach; ?>
//]]>
</script>
	
</td>
</tr>