<!--
/**
 * @category  Mbid
 * @package   Mbid_Magebid
 * @author    André Herrn <info@magebid.com>
 * @copyright 2010 André Herrn | Netresearch GmbH & Co.KG (http://www.netresearch.de)
 * @link      http://www.magebid.com/
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
-->

<div class="content-header">
    <h3 class="icon-head head-products"><?php echo $this->getHeaderText() ?></h3>
	<?php $button = $this->getSaveButton();?>
    <p class="content-buttons form-buttons"><button onclick="<?php echo $button['clickAction']; ?>" id="<?php echo $button['name'] ?>" type="button" class="scalable" style=""><span><?php echo $button['action'] ?></span></button>
</div>

<?php echo $this->getFormHtml(); ?>