<?php $_htmlId      = $this->getElement()->getHtmlId()?>
<?php $_htmlClass   = $this->getElement()->getClass()?>
<?php $_htmlName    = $this->getElement()->getName()?>
<?php $_allowEdit    = $this->getAllowEdit()?>

<tr>
    <td class="label"><?php echo Mage::helper('magebid')->__('Payment Methods') ?></td>
    <td colspan="10" class="grid payment">
    <table cellspacing="0" class="data border" id="payment_table">
        <col width="350" />
        <!--<col width="50" />-->
         <?php if ($_allowEdit): ?><col width="75" /><?php endif; ?>
        <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('magebid')->__('Payment Methods') ?></th>
                <!--<th><?php echo Mage::helper('magebid')->__('Payment Price') ?></th>-->
                 <?php if ($_allowEdit): ?><th class="last"><?php echo Mage::helper('catalog')->__('Action') ?></th><?php endif; ?>
            </tr>
            <tr id="<?php echo $_htmlId ?>_add_template" class="template no-display">
                <td>
                <select disabled="no-template" class="<?php echo $_htmlClass ?> paymethod required-entry" name="<?php echo $_htmlName ?>[__index__][payment_method]" id="payment_method_row___index___payment_methods">
                    <?php foreach ($this->getPaymentMethods() as $_paymentCode=>$_paymentDescription): ?>
                    <option value="<?php echo $_paymentCode ?>"><?php echo htmlspecialchars($_paymentDescription) ?></option>
                    <?php endforeach ?>
                </select>
                </td>
                <!--<td>
                    <input disabled="no-template" class="<?php echo $_htmlClass ?>" type="text" name="<?php echo $_htmlName ?>[__index__][price]" value="'#{price}'" />
                </td>-->
                <?php if ($_allowEdit): ?><td class="last"><input type="hidden" name="<?php echo $_htmlName ?>[__index__][delete]" class="delete" disabled="no-template" value="" /> <button title="Delete Payment Method" class="scalable delete icon-btn delete-payment-method" onclick="paymentMethodControl.deleteItem(event);return false"><span>Delete</span></button></td><?php endif; ?>
            </tr>
        </thead>
		<?php if ($_allowEdit): ?>
        <tfoot>
            <tr>
                <td colspan="4" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
            </tr>
        </tfoot>
		<?php endif; ?>
        <tbody id="<?php echo $_htmlId ?>_container">
        </tbody>
    </table>
	

<script type="text/javascript">
//<![CDATA[
    var paymentMethodControl = {
        template : new Template('<tr>' + $('<?php echo $_htmlId ?>_add_template').innerHTML.replace(/__index__/g, '#{index}').replace(/ disabled="?no-template"?/g, '').replace(/ disabled/g, '').replace(/="'([^']*)'"/g, '="$1"') + '</tr>'),
        itemsCount : 0,
        deleteButton: false,
        addItem  : function () {
            var data = {};
            data.payment = '';
            data.index = this.itemsCount++;
            if(arguments.length == 1) {
                data.payment      = arguments[0];
            }
            Element.insert($('<?php echo $_htmlId ?>_container'), {'bottom':this.template.evaluate(data)});
            $('payment_method_row_'+data.index+'_payment_methods').value = data.payment;
        },
        disableElement: function(elem) {
            elem.disabled = true
            elem.addClassName('disabled');
        },
        deleteItem : function(event) {
            var tr = Event.findElement(event, 'tr');
            if (tr) {
				//Element.remove(tr);
                Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                Element.hide(tr);
                Element.addClassName(tr, 'no-display template');	
            }
        }
    }
    <?php foreach ($this->getValues() as $_item): ?>
    paymentMethodControl.addItem('<?php echo $_item['payment_method'] ?>');
	<?php endforeach; ?>
</script>	
</td>
</tr>
