<?php
// autogenerated file 04.06.2009 09:55
// $Id: $
// $Log: $
//
//
require_once 'CalculatedHandlingDiscountType.php';
require_once 'AbstractResponseType.php';
require_once 'CalculatedShippingDiscountType.php';
require_once 'ShippingInsuranceType.php';
require_once 'CurrencyCodeType.php';
require_once 'CombinedPaymentPeriodCodeType.php';
require_once 'PromotionalShippingDiscountDetailsType.php';
require_once 'FlatShippingDiscountType.php';

/**
 * Response to call of GetShippingDiscountProfiles. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetShippingDiscountProfilesResponseType.html
 *
 */
class GetShippingDiscountProfilesResponseType extends AbstractResponseType
{
	/**
	 * @var CurrencyCodeType
	 */
	protected $CurrencyID;
	/**
	 * @var FlatShippingDiscountType
	 */
	protected $FlatShippingDiscount;
	/**
	 * @var CalculatedShippingDiscountType
	 */
	protected $CalculatedShippingDiscount;
	/**
	 * @var boolean
	 */
	protected $PromotionalShippingDiscount;
	/**
	 * @var CalculatedHandlingDiscountType
	 */
	protected $CalculatedHandlingDiscount;
	/**
	 * @var PromotionalShippingDiscountDetailsType
	 */
	protected $PromotionalShippingDiscountDetails;
	/**
	 * @var ShippingInsuranceType
	 */
	protected $ShippingInsurance;
	/**
	 * @var ShippingInsuranceType
	 */
	protected $InternationalShippingInsurance;
	/**
	 * @var CombinedPaymentPeriodCodeType
	 */
	protected $CombinedDuration;

	/**
	 * @return CurrencyCodeType
	 */
	function getCurrencyID()
	{
		return $this->CurrencyID;
	}
	/**
	 * @return void
	 * @param CurrencyCodeType $value 
	 */
	function setCurrencyID($value)
	{
		$this->CurrencyID = $value;
	}
	/**
	 * @return FlatShippingDiscountType
	 */
	function getFlatShippingDiscount()
	{
		return $this->FlatShippingDiscount;
	}
	/**
	 * @return void
	 * @param FlatShippingDiscountType $value 
	 */
	function setFlatShippingDiscount($value)
	{
		$this->FlatShippingDiscount = $value;
	}
	/**
	 * @return CalculatedShippingDiscountType
	 */
	function getCalculatedShippingDiscount()
	{
		return $this->CalculatedShippingDiscount;
	}
	/**
	 * @return void
	 * @param CalculatedShippingDiscountType $value 
	 */
	function setCalculatedShippingDiscount($value)
	{
		$this->CalculatedShippingDiscount = $value;
	}
	/**
	 * @return boolean
	 */
	function getPromotionalShippingDiscount()
	{
		return $this->PromotionalShippingDiscount;
	}
	/**
	 * @return void
	 * @param boolean $value 
	 */
	function setPromotionalShippingDiscount($value)
	{
		$this->PromotionalShippingDiscount = $value;
	}
	/**
	 * @return CalculatedHandlingDiscountType
	 */
	function getCalculatedHandlingDiscount()
	{
		return $this->CalculatedHandlingDiscount;
	}
	/**
	 * @return void
	 * @param CalculatedHandlingDiscountType $value 
	 */
	function setCalculatedHandlingDiscount($value)
	{
		$this->CalculatedHandlingDiscount = $value;
	}
	/**
	 * @return PromotionalShippingDiscountDetailsType
	 */
	function getPromotionalShippingDiscountDetails()
	{
		return $this->PromotionalShippingDiscountDetails;
	}
	/**
	 * @return void
	 * @param PromotionalShippingDiscountDetailsType $value 
	 */
	function setPromotionalShippingDiscountDetails($value)
	{
		$this->PromotionalShippingDiscountDetails = $value;
	}
	/**
	 * @return ShippingInsuranceType
	 */
	function getShippingInsurance()
	{
		return $this->ShippingInsurance;
	}
	/**
	 * @return void
	 * @param ShippingInsuranceType $value 
	 */
	function setShippingInsurance($value)
	{
		$this->ShippingInsurance = $value;
	}
	/**
	 * @return ShippingInsuranceType
	 */
	function getInternationalShippingInsurance()
	{
		return $this->InternationalShippingInsurance;
	}
	/**
	 * @return void
	 * @param ShippingInsuranceType $value 
	 */
	function setInternationalShippingInsurance($value)
	{
		$this->InternationalShippingInsurance = $value;
	}
	/**
	 * @return CombinedPaymentPeriodCodeType
	 */
	function getCombinedDuration()
	{
		return $this->CombinedDuration;
	}
	/**
	 * @return void
	 * @param CombinedPaymentPeriodCodeType $value 
	 */
	function setCombinedDuration($value)
	{
		$this->CombinedDuration = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetShippingDiscountProfilesResponseType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'CurrencyID' =>
					array(
						'required' => false,
						'type' => 'CurrencyCodeType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'FlatShippingDiscount' =>
					array(
						'required' => false,
						'type' => 'FlatShippingDiscountType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'CalculatedShippingDiscount' =>
					array(
						'required' => false,
						'type' => 'CalculatedShippingDiscountType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'PromotionalShippingDiscount' =>
					array(
						'required' => false,
						'type' => 'boolean',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'CalculatedHandlingDiscount' =>
					array(
						'required' => false,
						'type' => 'CalculatedHandlingDiscountType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'PromotionalShippingDiscountDetails' =>
					array(
						'required' => false,
						'type' => 'PromotionalShippingDiscountDetailsType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'ShippingInsurance' =>
					array(
						'required' => false,
						'type' => 'ShippingInsuranceType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'InternationalShippingInsurance' =>
					array(
						'required' => false,
						'type' => 'ShippingInsuranceType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'CombinedDuration' =>
					array(
						'required' => false,
						'type' => 'CombinedPaymentPeriodCodeType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
