<?php
// autogenerated file 04.06.2009 09:55
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Whether the alert is identifying a problem or is informational. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SellerDashboardAlertSeverityCodeType.html
 *
 * @property string Informational
 * @property string Warning
 * @property string StrongWarning
 * @property string CustomCode
 */
class SellerDashboardAlertSeverityCodeType extends EbatNs_FacetType
{
	const CodeType_Informational = 'Informational';
	const CodeType_Warning = 'Warning';
	const CodeType_StrongWarning = 'StrongWarning';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SellerDashboardAlertSeverityCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SellerDashboardAlertSeverityCodeType = new SellerDashboardAlertSeverityCodeType();

?>
