<?php
// autogenerated file 04.06.2009 09:55
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'URLTypeCodeType.php';

/**
 * Details about a specific eBay URL. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/URLDetailsType.html
 *
 */
class URLDetailsType extends EbatNs_ComplexType
{
	/**
	 * @var URLTypeCodeType
	 */
	protected $URLType;
	/**
	 * @var anyURI
	 */
	protected $URL;

	/**
	 * @return URLTypeCodeType
	 */
	function getURLType()
	{
		return $this->URLType;
	}
	/**
	 * @return void
	 * @param URLTypeCodeType $value 
	 */
	function setURLType($value)
	{
		$this->URLType = $value;
	}
	/**
	 * @return anyURI
	 */
	function getURL()
	{
		return $this->URL;
	}
	/**
	 * @return void
	 * @param anyURI $value 
	 */
	function setURL($value)
	{
		$this->URL = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('URLDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'URLType' =>
					array(
						'required' => false,
						'type' => 'URLTypeCodeType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'URL' =>
					array(
						'required' => false,
						'type' => 'anyURI',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
