<?php
// autogenerated file 04.06.2009 09:55
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'ItemIDType.php';

/**
 * Contains the item information to report. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/VeROReportItemType.html
 *
 */
class VeROReportItemType extends EbatNs_ComplexType
{
	/**
	 * @var ItemIDType
	 */
	protected $ItemID;
	/**
	 * @var long
	 */
	protected $VeROReasonCodeID;
	/**
	 * @var string
	 */
	protected $MessageToSeller;
	/**
	 * @var boolean
	 */
	protected $CopyEmailToRightsOwner;

	/**
	 * @return ItemIDType
	 */
	function getItemID()
	{
		return $this->ItemID;
	}
	/**
	 * @return void
	 * @param ItemIDType $value 
	 */
	function setItemID($value)
	{
		$this->ItemID = $value;
	}
	/**
	 * @return long
	 */
	function getVeROReasonCodeID()
	{
		return $this->VeROReasonCodeID;
	}
	/**
	 * @return void
	 * @param long $value 
	 */
	function setVeROReasonCodeID($value)
	{
		$this->VeROReasonCodeID = $value;
	}
	/**
	 * @return string
	 */
	function getMessageToSeller()
	{
		return $this->MessageToSeller;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setMessageToSeller($value)
	{
		$this->MessageToSeller = $value;
	}
	/**
	 * @return boolean
	 */
	function getCopyEmailToRightsOwner()
	{
		return $this->CopyEmailToRightsOwner;
	}
	/**
	 * @return void
	 * @param boolean $value 
	 */
	function setCopyEmailToRightsOwner($value)
	{
		$this->CopyEmailToRightsOwner = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('VeROReportItemType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'ItemID' =>
					array(
						'required' => false,
						'type' => 'ItemIDType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'VeROReasonCodeID' =>
					array(
						'required' => false,
						'type' => 'long',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'MessageToSeller' =>
					array(
						'required' => false,
						'type' => 'string',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'CopyEmailToRightsOwner' =>
					array(
						'required' => false,
						'type' => 'boolean',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
