<!--
/**
 * @category  Mbid
 * @package   Mbid_Magebid
 * @author    André Herrn <info@magebid.com>
 * @copyright 2010 André Herrn | Netresearch GmbH & Co.KG (http://www.netresearch.de)
 * @link      http://www.magebid.com/
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
-->

<?php echo $this->getChildHtml('form') ?>
<?php echo $this->getBlockHtml('formkey')?>

<script type="text/javascript">
function importAction(button)
    {
        $('task_action').value = button.id;
        $('configuration_form').submit();
}
</script>